/**
 * Copyright 2015-2016 Kaitai Project: MIT license
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package de.hub.se.jqf.bedivfuzz.examples.kaitai;

import java.nio.ByteBuffer;
import java.util.zip.CRC32;

/**
 * Common base class for all structured generated by Kaitai Struct.
 * Stores stream object that this object was parsed from in {@link #_io}.
 *
 * adapted from {@link edu.berkeley.cs.jqf.examples.kaitai.KaitaiStruct}
 */
public class SplitKaitaiStruct {
    /**
     * Stream object that this KaitaiStruct-based structure was parsed from.
     */
    protected SplitKaitaiStream _io;

    public SplitKaitaiStruct(SplitKaitaiStream _io) {
        this._io = _io;
    }

    public SplitKaitaiStream _io() { return _io; }

    protected byte[] writeCRC(int offset, int len) {
        CRC32 crc = new CRC32();
        crc.update(_io.buf.array(), offset, len);
        int crcValue = (int) crc.getValue();
        this._io.writeIntvalue(crcValue); // NOTE: Depends on endianness!
        return ByteBuffer.allocate(4).putInt(crcValue).array();
    }
}
